import { PrismaClient } from '@prisma/client';
import bcrypt from 'bcryptjs';

export async function seedDocentes(prisma: PrismaClient) {
  console.log('🌱 Sembrando Docentes y Usuarios (datos reales + estimados)...');

  function generarCorreo(nombres: string, apellidos: string): string {
    const nombreParts = nombres.trim().toLowerCase().split(/\s+/);
    const apellidoParts = apellidos.trim().toLowerCase().split(/\s+/);
    const inicialNombre = nombreParts[0].charAt(0);
    const primerApellido = apellidoParts[0];
    const segundoApellido = apellidoParts[1] || '';
    let base = inicialNombre + primerApellido + segundoApellido;
    base = base.normalize('NFD').replace(/[\u0300-\u036f]/g, '').replace(/[^a-z]/g, '');
    return `${base}@unitru.edu.pe`;
  }

  // Lista completa de docentes (datos reales de Excel para Sistemas + estimados para otros cursos)
  const docentesData = [
    // ========== DEPARTAMENTO DE INGENIERÍA DE SISTEMAS (extraído de los Excel) ==========
    {
      nombres: "Everson David",
      apellidos: "Agreda Gamboa",
      dni: "18161457",
      fecha_ingreso: new Date("2002-08-19"),
      modalidad: "nombrado",
      categoria: "principal",
      grado: "DOCTOR",
      especialidad: "Ingeniería de Sistemas",
    },
    {
      nombres: "Oscar Romel",
      apellidos: "Alcantara Moreno",
      dni: "18126940",
      fecha_ingreso: new Date("2011-04-25"),
      modalidad: "nombrado",
      categoria: "auxiliar",
      grado: "DOCTOR",
      especialidad: "Ingeniería de Sistemas",
    },
    {
      nombres: "Cesar",
      apellidos: "Arellano Salazar",
      dni: "18147714",
      fecha_ingreso: new Date("2002-04-23"),
      modalidad: "nombrado",
      categoria: "auxiliar",
      grado: null,
      especialidad: "Ingeniería de Sistemas",
    },
    {
      nombres: "Luis Enrique",
      apellidos: "Boy Chavil",
      dni: "18842081",
      fecha_ingreso: new Date("1999-10-05"),
      modalidad: "nombrado",
      categoria: "principal",
      grado: "DOCTOR",
      especialidad: "Ingeniería de Sistemas",
    },
    {
      nombres: "Victor Antonio",
      apellidos: "Charcape Ravelo",
      dni: "18069724",
      fecha_ingreso: new Date("2021-06-14"),
      modalidad: "contratado",
      categoria: "auxiliar",
      grado: "MAGISTER",
      especialidad: "Ingeniería de Sistemas",
    },
    {
      nombres: "Juan Luis",
      apellidos: "Cordova Otero",
      dni: "18122765",
      fecha_ingreso: new Date("2017-05-15"),
      modalidad: "nombrado",
      categoria: "auxiliar",
      grado: "MAGISTER",
      especialidad: "Ingeniería de Sistemas",
    },
    {
      nombres: "Franklin Alexis",
      apellidos: "Diaz Diaz",
      dni: "41556261",
      fecha_ingreso: new Date("2021-06-14"),
      modalidad: "contratado",
      categoria: "auxiliar",
      grado: "MAGISTER",
      especialidad: "Ingeniería de Sistemas",
    },
    {
      nombres: "Jose Alberto",
      apellidos: "Gomez Avila",
      dni: "40990648",
      fecha_ingreso: new Date("2013-05-15"),
      modalidad: "nombrado",
      categoria: "auxiliar",
      grado: "DOCTOR",
      especialidad: "Ingeniería de Sistemas",
    },
    {
      nombres: "Alberto Carlos",
      apellidos: "Mendoza de los Santos",
      dni: "17434055",
      fecha_ingreso: new Date("2011-09-05"),
      modalidad: "nombrado",
      categoria: "asociado",
      grado: "DOCTOR",
      especialidad: "Ingeniería de Sistemas",
    },
    {
      nombres: "Ricardo Dario",
      apellidos: "Mendoza Rivera",
      dni: "18070765",
      fecha_ingreso: new Date("2016-12-14"),
      modalidad: "nombrado",
      categoria: "asociado",
      grado: "DOCTOR",
      especialidad: "Ingeniería de Sistemas",
    },
    {
      nombres: "Juan Carlos",
      apellidos: "Obando Roldan",
      dni: "18122605",
      fecha_ingreso: new Date("2001-09-21"),
      modalidad: "nombrado",
      categoria: "principal",
      grado: "DOCTOR",
      especialidad: "Ingeniería de Sistemas",
    },
    {
      nombres: "Silvia Ana",
      apellidos: "Rodriguez Aguirre",
      dni: "18132421",
      fecha_ingreso: new Date("2013-04-01"),
      modalidad: "contratado",
      categoria: "auxiliar",
      grado: "MAGISTER",
      especialidad: "Ingeniería de Sistemas",
    },
    {
      nombres: "Robert Jerry",
      apellidos: "Sanchez Ticona",
      dni: "19082305",
      fecha_ingreso: new Date("2008-12-05"),
      modalidad: "nombrado",
      categoria: "asociado",
      grado: "MAGISTER",
      especialidad: "Ingeniería de Sistemas",
    },
    {
      nombres: "Juan Pedro",
      apellidos: "Santos Fernandez",
      dni: "17896289",
      fecha_ingreso: new Date("1992-07-07"),
      modalidad: "nombrado",
      categoria: "principal",
      grado: "DOCTOR",
      especialidad: "Ingeniería de Sistemas",
    },
    {
      nombres: "Camilo Ernesto",
      apellidos: "Suarez Rebaza",
      dni: "32978627",
      fecha_ingreso: new Date("2017-05-18"),
      modalidad: "nombrado",
      categoria: "auxiliar",
      grado: "MAGISTER",
      especialidad: "Ingeniería de Sistemas",
    },
    {
      nombres: "Marcelino",
      apellidos: "Torres Villanueva",
      dni: "17865408",
      fecha_ingreso: new Date("2006-01-03"),
      modalidad: "nombrado",
      categoria: "auxiliar",
      grado: "MAGISTER",
      especialidad: "Ingeniería de Sistemas",
    },
    {
      nombres: "Manuel Deivis",
      apellidos: "Ulloa Florian",
      dni: "42031507",
      fecha_ingreso: new Date("2024-10-01"),
      modalidad: "contratado",
      categoria: "auxiliar",
      grado: "MAGISTER",
      especialidad: "Ingeniería de Sistemas",
    },
    {
      nombres: "Zoraida Yanet",
      apellidos: "Vidal Melgarejo",
      dni: "18153095",
      fecha_ingreso: new Date("2002-04-22"),
      modalidad: "nombrado",
      categoria: "asociado",
      grado: "MAGISTER",
      especialidad: "Ingeniería de Sistemas",
    },

    // ========== DOCENTES DE OTROS DEPARTAMENTOS QUE ENSEÑAN EN SISTEMAS ==========
    // Los datos se extraen del Excel donde sea posible, de lo contrario se estiman.
    {
      nombres: "Bertha",
      apellidos: "Urtecho Zavaleta",
      dni: "18165597",
      fecha_ingreso: new Date("2010-03-01"),
      modalidad: "contratado",
      categoria: "asociado",
      grado: null,
      especialidad: "Psicología",
    },
    {
      nombres: "Jose Luis",
      apellidos: "Ponte Bejarano",
      dni: "43616041",
      fecha_ingreso: new Date("2012-03-01"),
      modalidad: "contratado",
      categoria: "principal",
      grado: "Licenciado en matemáticas",
      especialidad: "Matemáticas",
    },
    {
      nombres: "Jorge Luis",
      apellidos: "Rios Gonzales",
      dni: null,
      fecha_ingreso: new Date("2011-03-01"),
      modalidad: "contratado",
      categoria: "asociado",
      grado: null,
      especialidad: "Lengua y Literatura",
    },
    {
      nombres: "Segunda",
      apellidos: "Gubar Obeso",
      dni: null,
      fecha_ingreso: new Date("2000-03-01"),
      modalidad: "contratado",
      categoria: "principal",
      grado: null,
      especialidad: "Matemáticas",
    },
    {
      nombres: "Miguel",
      apellidos: "Ipanaque Zapata",
      dni: null,
      fecha_ingreso: new Date("2013-03-01"),
      modalidad: "contratado",
      categoria: "asociado",
      grado: null,
      especialidad: "Estadística",
    },
    {
      nombres: "Martha",
      apellidos: "Cardoso",
      dni: null,
      fecha_ingreso: new Date("2018-03-01"),
      modalidad: "contratado",
      categoria: "auxiliar",
      grado: null,
      especialidad: "Estadística",
    },
    {
      nombres: "Marcos",
      apellidos: "Ferrer Reyna",
      dni: null,
      fecha_ingreso: new Date("2019-03-01"),
      modalidad: "contratado",
      categoria: "auxiliar",
      grado: null,
      especialidad: "Matemáticas",
    },
    {
      nombres: "Teresita",
      apellidos: "Rojas García",
      dni: null,
      fecha_ingreso: new Date("2014-03-01"),
      modalidad: "contratado",
      categoria: "asociado",
      grado: null,
      especialidad: "Estadística",
    },
    {
      nombres: "Juan",
      apellidos: "Carrascal Cabanillas",
      dni: null,
      fecha_ingreso: new Date("2015-03-01"),
      modalidad: "contratado",
      categoria: "auxiliar",
      grado: null,
      especialidad: "Administración",
    },
    {
      nombres: "Vilma",
      apellidos: "Mendez Gil",
      dni: null,
      fecha_ingreso: new Date("2016-03-01"),
      modalidad: "contratado",
      categoria: "asociado",
      grado: null,
      especialidad: "Física",
    },
    {
      nombres: "Sheyla Laura",
      apellidos: "Escobedo Rodríguez",
      dni: null,
      fecha_ingreso: new Date("2019-03-01"),
      modalidad: "contratado",
      categoria: "auxiliar",
      grado: null,
      especialidad: "Psicología",
    },
    {
      nombres: "Marcos",
      apellidos: "Baca Lopez",
      dni: null,
      fecha_ingreso: new Date("2017-03-01"),
      modalidad: "contratado",
      categoria: "auxiliar",
      grado: null,
      especialidad: "Ingeniería Industrial",
    },
    {
      nombres: "Ana",
      apellidos: "Cuadra Mitzugaray",
      dni: null,
      fecha_ingreso: new Date("2018-03-01"),
      modalidad: "contratado",
      categoria: "auxiliar",
      grado: null,
      especialidad: "Contabilidad y Finanzas",
    },
    {
      nombres: "Jhoe Alexis",
      apellidos: "González Vásquez",
      dni: null,
      fecha_ingreso: new Date("2015-03-01"),
      modalidad: "contratado",
      categoria: "auxiliar",
      grado: null,
      especialidad: "Ingeniería Industrial",
    },
    {
      nombres: "Segundo",
      apellidos: "Roseli Jauregui Rosas",
      dni: null,
      fecha_ingreso: new Date("2016-03-01"),
      modalidad: "contratado",
      categoria: "auxiliar",
      grado: null,
      especialidad: "Física",
    },
    {
      nombres: "Edgard",
      apellidos: "Pelaez Vinces",
      dni: null,
      fecha_ingreso: new Date("2018-03-01"),
      modalidad: "contratado",
      categoria: "auxiliar",
      grado: null,
      especialidad: "Ciencias Sociales",
    },
    {
      nombres: "Diego",
      apellidos: "Llaro Cruz",
      dni: null,
      fecha_ingreso: new Date("2019-03-01"),
      modalidad: "contratado",
      categoria: "auxiliar",
      grado: null,
      especialidad: "Educación",
    },
    {
      nombres: "Alex",
      apellidos: "Herradas",
      dni: null,
      fecha_ingreso: new Date("2017-03-01"),
      modalidad: "contratado",
      categoria: "auxiliar",
      grado: null,
      especialidad: "Filosofía",
    },
    {
      nombres: "Miltón",
      apellidos: "Cortez",
      dni: null,
      fecha_ingreso: new Date("2014-03-01"),
      modalidad: "contratado",
      categoria: "auxiliar",
      grado: null,
      especialidad: "Matemáticas",
    },
    {
      nombres: "Aristeres",
      apellidos: "Tavara Aponte",
      dni: null,
      fecha_ingreso: new Date("2016-03-01"),
      modalidad: "contratado",
      categoria: "auxiliar",
      grado: null,
      especialidad: "Física",
    },
    {
      nombres: "Kevin Litman",
      apellidos: "Florez Tolentino",
      dni: null,
      fecha_ingreso: new Date("2019-03-01"),
      modalidad: "contratado",
      categoria: "auxiliar",
      grado: null,
      especialidad: "Contabilidad y Finanzas",
    },
    {
      nombres: "Juan",
      apellidos: "Cabanillas",
      dni: null,
      fecha_ingreso: new Date("2015-03-01"),
      modalidad: "contratado",
      categoria: "auxiliar",
      grado: null,
      especialidad: "Administración",
    },
    {
      nombres: "Luis",
      apellidos: "Moncada Alvites",
      dni: null,
      fecha_ingreso: new Date("2017-03-01"),
      modalidad: "contratado",
      categoria: "auxiliar",
      grado: null,
      especialidad: "Ingeniería Ambiental",
    },
    {
      nombres: "Marco",
      apellidos: "Celi Arevalo",
      dni: null,
      fecha_ingreso: new Date("2018-03-01"),
      modalidad: "contratado",
      categoria: "auxiliar",
      grado: null,
      especialidad: "Derecho",
    },
    {
      nombres: "Jorge Paul",
      apellidos: "Cotrina Castellanos",
      dni: null,
      fecha_ingreso: new Date("2016-03-01"),
      modalidad: "contratado",
      categoria: "auxiliar",
      grado: null,
      especialidad: "Ingeniería de Sistemas",
    },
    {
      nombres: "Paul",
      apellidos: "Cotrina Castellanos",
      dni: null,
      fecha_ingreso: new Date("2020-03-01"),
      modalidad: "contratado",
      categoria: "auxiliar",
      grado: null,
      especialidad: "Ingeniería de Sistemas",
    },
  ];
  for (const data of docentesData) {
    const primerNombre = data.nombres.split(' ')[0];
    const inicial = primerNombre.charAt(0).toLowerCase();
    const dni = data.dni ?? null;
    const codigoDocente = dni ? `${inicial}${dni}` : `${inicial}99999999`;

    const correo = generarCorreo(data.nombres, data.apellidos);
    const contrasenaHash = await bcrypt.hash(dni ?? codigoDocente, 10);

    const usuario = await prisma.usuario.upsert({
      where: { correo_electronico: correo },
      update: {
        nombres: data.nombres,
        apellidos: data.apellidos,
        ...(dni !== null ? { dni } : {}),
        contrasena_hash: contrasenaHash,
        rol: 'docente',
      },
      create: {
        codigo: `USR_${Date.now()}_${Math.random().toString(36).substr(2, 5)}`,
        nombres: data.nombres,
        apellidos: data.apellidos,
        ...(dni !== null ? { dni } : {}),
        correo_electronico: correo,
        contrasena_hash: contrasenaHash,
        rol: 'docente',
      },
    });

    await prisma.docente.upsert({
      where: { codigo_docente: codigoDocente },
      update: {
        id_usuario: usuario.id_usuario,
        nombres: data.nombres,
        apellidos: data.apellidos,
        modalidad: data.modalidad,
        categoria: data.categoria,
        fecha_ingreso: data.fecha_ingreso,
        grado_academico: data.grado,
        especialidad: data.especialidad,
        correo_electronico: correo,
        dni,
      },
      create: {
        codigo_docente: codigoDocente,
        id_usuario: usuario.id_usuario,
        nombres: data.nombres,
        apellidos: data.apellidos,
        modalidad: data.modalidad,
        categoria: data.categoria,
        fecha_ingreso: data.fecha_ingreso,
        grado_academico: data.grado,
        especialidad: data.especialidad,
        correo_electronico: correo,
        dni,
      },
    });
    console.log(`✅ Docente: ${data.nombres} ${data.apellidos} (${correo}) - Ingreso: ${data.fecha_ingreso?.toISOString().split('T')[0] || 'N/D'}`);
  }

  const total = await prisma.docente.count();
  console.log(`✅ ${total} docentes sembrados.\n`);
  return total;
}